application: p2psalt
version: 1
runtime: python
api_version: 1

handlers:

- url: /api/.*
  script: api.py

# index files

- url: /
  static_files: brunch/index.html
  upload: brunch/index.html

- url: /favicon.ico
  static_files: brunch/favicon.ico
  upload: brunch/index.html

- url: /
  static_dir: brunch
  
